In [3]:
import numpy as np

def standardize(X):
    return (X - np.mean(X, axis=0)) / np.std(X, axis=0)

def compute_covariance_matrix(X):
    return np.cov(X.T)

def find_eigenvectors_and_eigenvalues(X):
    cov_matrix = compute_covariance_matrix(X)
    eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
    return eigenvalues, eigenvectors

def project_data(X, eigenvectors, k):
    sorted_indices = np.argsort(-eigenvalues)[:k]
    sorted_eigenvectors = eigenvectors[:, sorted_indices]
    return np.dot(X, sorted_eigenvectors)

def get_variance_explained(eigenvalues, k):
    return sum(eigenvalues[:k]) / sum(eigenvalues)

X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
X_std = standardize(X)
eigenvalues, eigenvectors = find_eigenvectors_and_eigenvalues(X_std)
projected_data = project_data(X_std, eigenvectors, 2)
variance_explained = get_variance_explained(eigenvalues, 2)

print("Standardized data:")
print(X_std)
print("Covariance matrix:")
print(compute_covariance_matrix(X_std))
print("Eigenvalues:")
print(eigenvalues)
print("Eigenvectors:")
print(eigenvectors)
print("Projected data:")
print(projected_data)
print("Variance explained:")
print(variance_explained)


Standardized data:
[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]
Covariance matrix:
[[1.5 1.5 1.5]
 [1.5 1.5 1.5]
 [1.5 1.5 1.5]]
Eigenvalues:
[ 4.50000000e+00 -8.02577045e-18  3.08148791e-32]
Eigenvectors:
[[ 5.77350269e-01 -1.81919449e-01  6.86994728e-16]
 [ 5.77350269e-01 -5.98372551e-01 -7.07106781e-01]
 [ 5.77350269e-01  7.80292000e-01  7.07106781e-01]]
Projected data:
[[-2.12132034e+00  2.11167406e-17]
 [ 0.00000000e+00  0.00000000e+00]
 [ 2.12132034e+00 -2.11167406e-17]]
Variance explained:
1.0


In [9]:
import numpy as np # Predefined dataset dataset = np.array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9],
[10, 11, 12]
])
# Calculate the covariance matrix
covariance_matrix = np.cov(dataset, rowvar=False)
Print the covariance matrix print("Covariance Matrix:") print(covariance_matrix)


SyntaxError: unmatched ']' (3632303104.py, line 6)